### ISSUE TITLE
Nitpick: Circle to use fill instead of stroke

### ISSUE THREAD

**Issue by ersin-ertan** [deepakbaliga/BeautifulGraphSample#1]
In the png, some of the circles that have lines connecting to them at acute angle show the white space. Perhaps a filled circle would look more consistent with regards to whole graph.

**Comment by deepakbaliga** [comment]
@ersin-ertan . Thank you. I will fix it soon.

**Comment by deepakbaliga** [comment]
This issue has been fixed. Thank you again.
